// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A Memorystore for Redis instance.
public struct Instance: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Unique name of the resource in this scope including project and
  /// location using the form:
  ///     `projects/{project_id}/locations/{location_id}/instances/{instance_id}`
  ///
  /// Note: Redis instances are managed and addressed at regional level so
  /// location_id here refers to a GCP region; however, users may choose which
  /// specific zone (or collection of zones for cross-zone instances) an instance
  /// should be provisioned in. Refer to
  /// [location_id][google.cloud.redis.v1.Instance.location_id] and
  /// [alternative_location_id][google.cloud.redis.v1.Instance.alternative_location_id]
  /// fields for more details.
  ///
  /// [google.cloud.redis.v1.Instance.alternative_location_id]: <doc:Instance/alternativeLocationId>
  /// [google.cloud.redis.v1.Instance.location_id]: <doc:Instance/locationId>
  public var name: Swift.String = Swift.String()

  /// An arbitrary and optional user-provided name for the instance.
  public var displayName: Swift.String = Swift.String()

  /// Resource labels to represent user provided metadata
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. The zone where the instance will be provisioned. If not provided,
  /// the service will choose a zone from the specified region for the instance.
  /// For standard tier, additional nodes will be added across multiple zones for
  /// protection against zonal failures. If specified, at least one node will be
  /// provisioned in this zone.
  public var locationId: Swift.String = Swift.String()

  /// Optional. If specified, at least one node will be provisioned in this zone
  /// in addition to the zone specified in location_id. Only applicable to
  /// standard tier. If provided, it must be a different zone from the one
  /// provided in [location_id]. Additional nodes beyond the first 2 will be
  /// placed in zones selected by the service.
  public var alternativeLocationId: Swift.String = Swift.String()

  /// Optional. The version of Redis software.
  /// If not provided, latest supported version will be used. Currently, the
  /// supported values are:
  ///
  ///  *   `REDIS_3_2` for Redis 3.2 compatibility
  ///  *   `REDIS_4_0` for Redis 4.0 compatibility (default)
  ///  *   `REDIS_5_0` for Redis 5.0 compatibility
  ///  *   `REDIS_6_X` for Redis 6.x compatibility
  public var redisVersion: Swift.String = Swift.String()

  /// Optional. For DIRECT_PEERING mode, the CIDR range of internal addresses
  /// that are reserved for this instance. Range must
  /// be unique and non-overlapping with existing subnets in an authorized
  /// network. For PRIVATE_SERVICE_ACCESS mode, the name of one allocated IP
  /// address ranges associated with this private service access connection.
  /// If not provided, the service will choose an unused /29 block, for
  /// example, 10.0.0.0/29 or 192.168.0.0/29.  For READ_REPLICAS_ENABLED
  /// the default block size is /28.
  public var reservedIpRange: Swift.String = Swift.String()

  /// Optional. Additional IP range for node placement. Required when enabling
  /// read replicas on an existing instance. For DIRECT_PEERING mode value must
  /// be a CIDR range of size /28, or "auto". For PRIVATE_SERVICE_ACCESS mode
  /// value must be the name of an allocated address range associated with the
  /// private service access connection, or "auto".
  public var secondaryIpRange: Swift.String = Swift.String()

  /// Output only. Hostname or IP address of the exposed Redis endpoint used by
  /// clients to connect to the service.
  public var host: Swift.String = Swift.String()

  /// Output only. The port number of the exposed Redis endpoint.
  public var port: Swift.Int32 = Swift.Int32()

  /// Output only. The current zone where the Redis primary node is located. In
  /// basic tier, this will always be the same as [location_id]. In
  /// standard tier, this can be the zone of any node in the instance.
  public var currentLocationId: Swift.String = Swift.String()

  /// Output only. The time the instance was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The current state of this instance.
  public var state: Instance.State = Instance.State()

  /// Output only. Additional information about the current status of this
  /// instance, if available.
  public var statusMessage: Swift.String = Swift.String()

  /// Optional. Redis configuration parameters, according to
  /// http://redis.io/topics/config. Currently, the only supported parameters
  /// are:
  ///
  ///  Redis version 3.2 and newer:
  ///
  ///  *   maxmemory-policy
  ///  *   notify-keyspace-events
  ///
  ///  Redis version 4.0 and newer:
  ///
  ///  *   activedefrag
  ///  *   lfu-decay-time
  ///  *   lfu-log-factor
  ///  *   maxmemory-gb
  ///
  ///  Redis version 5.0 and newer:
  ///
  ///  *   stream-node-max-bytes
  ///  *   stream-node-max-entries
  public var redisConfigs: [Swift.String: Swift.String] = [:]

  /// Required. The service tier of the instance.
  public var tier: Instance.Tier = Instance.Tier()

  /// Required. Redis memory size in GiB.
  public var memorySizeGb: Swift.Int32 = Swift.Int32()

  /// Optional. The full name of the Google Compute Engine
  /// [network](https://cloud.google.com/vpc/docs/vpc) to which the
  /// instance is connected. If left unspecified, the `default` network
  /// will be used.
  public var authorizedNetwork: Swift.String = Swift.String()

  /// Output only. Cloud IAM identity used by import / export operations to
  /// transfer data to/from Cloud Storage. Format is
  /// "serviceAccount:<service_account_email>". The value may change over time
  /// for a given instance so should be checked before each import/export
  /// operation.
  public var persistenceIamIdentity: Swift.String = Swift.String()

  /// Optional. The network connect mode of the Redis instance.
  /// If not provided, the connect mode defaults to DIRECT_PEERING.
  public var connectMode: Instance.ConnectMode = Instance.ConnectMode()

  /// Optional. Indicates whether OSS Redis AUTH is enabled for the instance. If
  /// set to "true" AUTH is enabled on the instance. Default value is "false"
  /// meaning AUTH is disabled.
  public var authEnabled: Swift.Bool = Swift.Bool()

  /// Output only. List of server CA certificates for the instance.
  public var serverCaCerts: [TlsCertificate] = []

  /// Optional. The TLS mode of the Redis instance.
  /// If not provided, TLS is disabled for the instance.
  public var transitEncryptionMode: Instance.TransitEncryptionMode =
    Instance.TransitEncryptionMode()

  /// Optional. The maintenance policy for the instance. If not provided,
  /// maintenance events can be performed at any time.
  public var maintenancePolicy: MaintenancePolicy? = nil

  /// Output only. Date and time of upcoming maintenance events which have been
  /// scheduled.
  public var maintenanceSchedule: MaintenanceSchedule? = nil

  /// Optional. The number of replica nodes. The valid range for the Standard
  /// Tier with read replicas enabled is [1-5] and defaults to 2. If read
  /// replicas are not enabled for a Standard Tier instance, the only valid value
  /// is 1 and the default is 1. The valid value for basic tier is 0 and the
  /// default is also 0.
  public var replicaCount: Swift.Int32 = Swift.Int32()

  /// Output only. Info per node.
  public var nodes: [NodeInfo] = []

  /// Output only. Hostname or IP address of the exposed readonly Redis
  /// endpoint. Standard tier only. Targets all healthy replica nodes in
  /// instance. Replication is asynchronous and replica nodes will exhibit some
  /// lag behind the primary. Write requests must target 'host'.
  public var readEndpoint: Swift.String = Swift.String()

  /// Output only. The port number of the exposed readonly redis
  /// endpoint. Standard tier only. Write requests should target 'port'.
  public var readEndpointPort: Swift.Int32 = Swift.Int32()

  /// Optional. Read replicas mode for the instance. Defaults to
  /// READ_REPLICAS_DISABLED.
  public var readReplicasMode: Instance.ReadReplicasMode = Instance.ReadReplicasMode()

  /// Optional. The KMS key reference that the customer provides when trying to
  /// create the instance.
  public var customerManagedKey: Swift.String = Swift.String()

  /// Optional. Persistence configuration parameters
  public var persistenceConfig: PersistenceConfig? = nil

  /// Optional. reasons that causes instance in "SUSPENDED" state.
  public var suspensionReasons: [Instance.SuspensionReason] = []

  /// Optional. The self service update maintenance version.
  /// The version is date based such as "20210712_00_00".
  public var maintenanceVersion: Swift.String = Swift.String()

  /// Optional. The available maintenance versions that an instance could update
  /// to.
  public var availableMaintenanceVersions: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let labels = CodingKeys(stringValue: "labels")
    static let locationId = CodingKeys(stringValue: "locationId")
    static let alternativeLocationId = CodingKeys(stringValue: "alternativeLocationId")
    static let redisVersion = CodingKeys(stringValue: "redisVersion")
    static let reservedIpRange = CodingKeys(stringValue: "reservedIpRange")
    static let secondaryIpRange = CodingKeys(stringValue: "secondaryIpRange")
    static let host = CodingKeys(stringValue: "host")
    static let port = CodingKeys(stringValue: "port")
    static let currentLocationId = CodingKeys(stringValue: "currentLocationId")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let state = CodingKeys(stringValue: "state")
    static let statusMessage = CodingKeys(stringValue: "statusMessage")
    static let redisConfigs = CodingKeys(stringValue: "redisConfigs")
    static let tier = CodingKeys(stringValue: "tier")
    static let memorySizeGb = CodingKeys(stringValue: "memorySizeGb")
    static let authorizedNetwork = CodingKeys(stringValue: "authorizedNetwork")
    static let persistenceIamIdentity = CodingKeys(stringValue: "persistenceIamIdentity")
    static let connectMode = CodingKeys(stringValue: "connectMode")
    static let authEnabled = CodingKeys(stringValue: "authEnabled")
    static let serverCaCerts = CodingKeys(stringValue: "serverCaCerts")
    static let transitEncryptionMode = CodingKeys(stringValue: "transitEncryptionMode")
    static let maintenancePolicy = CodingKeys(stringValue: "maintenancePolicy")
    static let maintenanceSchedule = CodingKeys(stringValue: "maintenanceSchedule")
    static let replicaCount = CodingKeys(stringValue: "replicaCount")
    static let nodes = CodingKeys(stringValue: "nodes")
    static let readEndpoint = CodingKeys(stringValue: "readEndpoint")
    static let readEndpointPort = CodingKeys(stringValue: "readEndpointPort")
    static let readReplicasMode = CodingKeys(stringValue: "readReplicasMode")
    static let customerManagedKey = CodingKeys(stringValue: "customerManagedKey")
    static let persistenceConfig = CodingKeys(stringValue: "persistenceConfig")
    static let suspensionReasons = CodingKeys(stringValue: "suspensionReasons")
    static let maintenanceVersion = CodingKeys(stringValue: "maintenanceVersion")
    static let availableMaintenanceVersions = CodingKeys(
      stringValue: "availableMaintenanceVersions")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "labels",
      "locationId",
      "alternativeLocationId",
      "redisVersion",
      "reservedIpRange",
      "secondaryIpRange",
      "host",
      "port",
      "currentLocationId",
      "createTime",
      "state",
      "statusMessage",
      "redisConfigs",
      "tier",
      "memorySizeGb",
      "authorizedNetwork",
      "persistenceIamIdentity",
      "connectMode",
      "authEnabled",
      "serverCaCerts",
      "transitEncryptionMode",
      "maintenancePolicy",
      "maintenanceSchedule",
      "replicaCount",
      "nodes",
      "readEndpoint",
      "readEndpointPort",
      "readReplicasMode",
      "customerManagedKey",
      "persistenceConfig",
      "suspensionReasons",
      "maintenanceVersion",
      "availableMaintenanceVersions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .locationId) {
      self.locationId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .alternativeLocationId)
    {
      self.alternativeLocationId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .redisVersion) {
      self.redisVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .reservedIpRange) {
      self.reservedIpRange = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secondaryIpRange) {
      self.secondaryIpRange = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .host) {
      self.host = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .port) {
      self.port = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .currentLocationId) {
      self.currentLocationId = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(Instance.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .statusMessage) {
      self.statusMessage = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .redisConfigs)
    {
      self.redisConfigs = value
    }
    if let value = try container.decodeIfPresent(Instance.Tier.self, forKey: .tier) {
      self.tier = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .memorySizeGb) {
      self.memorySizeGb = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .authorizedNetwork) {
      self.authorizedNetwork = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .persistenceIamIdentity)
    {
      self.persistenceIamIdentity = value
    }
    if let value = try container.decodeIfPresent(Instance.ConnectMode.self, forKey: .connectMode) {
      self.connectMode = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .authEnabled) {
      self.authEnabled = value
    }
    if let value = try container.decodeIfPresent([TlsCertificate].self, forKey: .serverCaCerts) {
      self.serverCaCerts = value
    }
    if let value = try container.decodeIfPresent(
      Instance.TransitEncryptionMode.self, forKey: .transitEncryptionMode)
    {
      self.transitEncryptionMode = value
    }
    self.maintenancePolicy = try container.decodeIfPresent(
      MaintenancePolicy.self, forKey: .maintenancePolicy)
    self.maintenanceSchedule = try container.decodeIfPresent(
      MaintenanceSchedule.self, forKey: .maintenanceSchedule)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .replicaCount) {
      self.replicaCount = value
    }
    if let value = try container.decodeIfPresent([NodeInfo].self, forKey: .nodes) {
      self.nodes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .readEndpoint) {
      self.readEndpoint = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .readEndpointPort) {
      self.readEndpointPort = value
    }
    if let value = try container.decodeIfPresent(
      Instance.ReadReplicasMode.self, forKey: .readReplicasMode)
    {
      self.readReplicasMode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .customerManagedKey) {
      self.customerManagedKey = value
    }
    self.persistenceConfig = try container.decodeIfPresent(
      PersistenceConfig.self, forKey: .persistenceConfig)
    if let value = try container.decodeIfPresent(
      [Instance.SuspensionReason].self, forKey: .suspensionReasons)
    {
      self.suspensionReasons = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .maintenanceVersion) {
      self.maintenanceVersion = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .availableMaintenanceVersions)
    {
      self.availableMaintenanceVersions = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.locationId, forKey: .locationId)
    try container.encode(self.alternativeLocationId, forKey: .alternativeLocationId)
    try container.encode(self.redisVersion, forKey: .redisVersion)
    try container.encode(self.reservedIpRange, forKey: .reservedIpRange)
    try container.encode(self.secondaryIpRange, forKey: .secondaryIpRange)
    try container.encode(self.host, forKey: .host)
    try container.encode(self.port, forKey: .port)
    try container.encode(self.currentLocationId, forKey: .currentLocationId)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.statusMessage, forKey: .statusMessage)
    try container.encode(self.redisConfigs, forKey: .redisConfigs)
    try container.encode(self.tier, forKey: .tier)
    try container.encode(self.memorySizeGb, forKey: .memorySizeGb)
    try container.encode(self.authorizedNetwork, forKey: .authorizedNetwork)
    try container.encode(self.persistenceIamIdentity, forKey: .persistenceIamIdentity)
    try container.encode(self.connectMode, forKey: .connectMode)
    try container.encode(self.authEnabled, forKey: .authEnabled)
    try container.encode(self.serverCaCerts, forKey: .serverCaCerts)
    try container.encode(self.transitEncryptionMode, forKey: .transitEncryptionMode)
    try container.encodeIfPresent(self.maintenancePolicy, forKey: .maintenancePolicy)
    try container.encodeIfPresent(self.maintenanceSchedule, forKey: .maintenanceSchedule)
    try container.encode(self.replicaCount, forKey: .replicaCount)
    try container.encode(self.nodes, forKey: .nodes)
    try container.encode(self.readEndpoint, forKey: .readEndpoint)
    try container.encode(self.readEndpointPort, forKey: .readEndpointPort)
    try container.encode(self.readReplicasMode, forKey: .readReplicasMode)
    try container.encode(self.customerManagedKey, forKey: .customerManagedKey)
    try container.encodeIfPresent(self.persistenceConfig, forKey: .persistenceConfig)
    try container.encode(self.suspensionReasons, forKey: .suspensionReasons)
    try container.encode(self.maintenanceVersion, forKey: .maintenanceVersion)
    try container.encode(self.availableMaintenanceVersions, forKey: .availableMaintenanceVersions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents the different states of a Redis instance.
  public enum State: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Redis instance is being created.
    case creating
    /// Redis instance has been created and is fully usable.
    case ready
    /// Redis instance configuration is being updated. Certain kinds of updates
    /// may cause the instance to become unusable while the update is in
    /// progress.
    case updating
    /// Redis instance is being deleted.
    case deleting
    /// Redis instance is being repaired and may be unusable.
    case repairing
    /// Maintenance is being performed on this Redis instance.
    case maintenance
    /// Redis instance is importing data (availability may be affected).
    case importing
    /// Redis instance is failing over (availability may be affected).
    case failingOver
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .ready: return 2
      case .updating: return 3
      case .deleting: return 4
      case .repairing: return 5
      case .maintenance: return 6
      case .importing: return 8
      case .failingOver: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .ready: return "READY"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .repairing: return "REPAIRING"
      case .maintenance: return "MAINTENANCE"
      case .importing: return "IMPORTING"
      case .failingOver: return "FAILING_OVER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "READY": self = .ready
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "REPAIRING": self = .repairing
      case "MAINTENANCE": self = .maintenance
      case "IMPORTING": self = .importing
      case "FAILING_OVER": self = .failingOver
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .ready
      case 3: self = .updating
      case 4: self = .deleting
      case 5: self = .repairing
      case 6: self = .maintenance
      case 8: self = .importing
      case 9: self = .failingOver
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .ready: return try container.encode("READY")
      case .updating: return try container.encode("UPDATING")
      case .deleting: return try container.encode("DELETING")
      case .repairing: return try container.encode("REPAIRING")
      case .maintenance: return try container.encode("MAINTENANCE")
      case .importing: return try container.encode("IMPORTING")
      case .failingOver: return try container.encode("FAILING_OVER")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Available service tiers to choose from
  public enum Tier: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// BASIC tier: standalone instance
    case basic
    /// STANDARD_HA tier: highly available primary/replica instances
    case standardHa
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .basic: return 1
      case .standardHa: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TIER_UNSPECIFIED"
      case .basic: return "BASIC"
      case .standardHa: return "STANDARD_HA"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Tier/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TIER_UNSPECIFIED": self = .unspecified
      case "BASIC": self = .basic
      case "STANDARD_HA": self = .standardHa
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Tier/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .basic
      case 3: self = .standardHa
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TIER_UNSPECIFIED")
      case .basic: return try container.encode("BASIC")
      case .standardHa: return try container.encode("STANDARD_HA")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Available connection modes.
  public enum ConnectMode: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Connect via direct peering to the Memorystore for Redis hosted service.
    case directPeering
    /// Connect your Memorystore for Redis instance using Private Service
    /// Access. Private services access provides an IP address range for multiple
    /// Google Cloud services, including Memorystore.
    case privateServiceAccess
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .directPeering: return 1
      case .privateServiceAccess: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONNECT_MODE_UNSPECIFIED"
      case .directPeering: return "DIRECT_PEERING"
      case .privateServiceAccess: return "PRIVATE_SERVICE_ACCESS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConnectMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONNECT_MODE_UNSPECIFIED": self = .unspecified
      case "DIRECT_PEERING": self = .directPeering
      case "PRIVATE_SERVICE_ACCESS": self = .privateServiceAccess
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConnectMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .directPeering
      case 2: self = .privateServiceAccess
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CONNECT_MODE_UNSPECIFIED")
      case .directPeering: return try container.encode("DIRECT_PEERING")
      case .privateServiceAccess: return try container.encode("PRIVATE_SERVICE_ACCESS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Available TLS modes.
  public enum TransitEncryptionMode: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Client to Server traffic encryption enabled with server authentication.
    case serverAuthentication
    /// TLS is disabled for the instance.
    case disabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .serverAuthentication: return 1
      case .disabled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TRANSIT_ENCRYPTION_MODE_UNSPECIFIED"
      case .serverAuthentication: return "SERVER_AUTHENTICATION"
      case .disabled: return "DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TransitEncryptionMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TRANSIT_ENCRYPTION_MODE_UNSPECIFIED": self = .unspecified
      case "SERVER_AUTHENTICATION": self = .serverAuthentication
      case "DISABLED": self = .disabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TransitEncryptionMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .serverAuthentication
      case 2: self = .disabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TRANSIT_ENCRYPTION_MODE_UNSPECIFIED")
      case .serverAuthentication: return try container.encode("SERVER_AUTHENTICATION")
      case .disabled: return try container.encode("DISABLED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Read replicas mode.
  public enum ReadReplicasMode: Codable, Equatable, Sendable {
    /// If not set, Memorystore Redis backend will default to
    /// READ_REPLICAS_DISABLED.
    case unspecified
    /// If disabled, read endpoint will not be provided and the instance cannot
    /// scale up or down the number of replicas.
    case readReplicasDisabled
    /// If enabled, read endpoint will be provided and the instance can scale
    /// up and down the number of replicas. Not valid for basic tier.
    case readReplicasEnabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .readReplicasDisabled: return 1
      case .readReplicasEnabled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "READ_REPLICAS_MODE_UNSPECIFIED"
      case .readReplicasDisabled: return "READ_REPLICAS_DISABLED"
      case .readReplicasEnabled: return "READ_REPLICAS_ENABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ReadReplicasMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "READ_REPLICAS_MODE_UNSPECIFIED": self = .unspecified
      case "READ_REPLICAS_DISABLED": self = .readReplicasDisabled
      case "READ_REPLICAS_ENABLED": self = .readReplicasEnabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ReadReplicasMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .readReplicasDisabled
      case 2: self = .readReplicasEnabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("READ_REPLICAS_MODE_UNSPECIFIED")
      case .readReplicasDisabled: return try container.encode("READ_REPLICAS_DISABLED")
      case .readReplicasEnabled: return try container.encode("READ_REPLICAS_ENABLED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Possible reasons for the instance to be in a "SUSPENDED" state.
  public enum SuspensionReason: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Something wrong with the CMEK key provided by customer.
    case customerManagedKeyIssue
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .customerManagedKeyIssue: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SUSPENSION_REASON_UNSPECIFIED"
      case .customerManagedKeyIssue: return "CUSTOMER_MANAGED_KEY_ISSUE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SuspensionReason/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SUSPENSION_REASON_UNSPECIFIED": self = .unspecified
      case "CUSTOMER_MANAGED_KEY_ISSUE": self = .customerManagedKeyIssue
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SuspensionReason/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .customerManagedKeyIssue
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SUSPENSION_REASON_UNSPECIFIED")
      case .customerManagedKeyIssue: return try container.encode("CUSTOMER_MANAGED_KEY_ISSUE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.v1.Instance"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
