// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Upcoming maintenance schedule. If no maintenance is scheduled, fields are not
/// populated.
public struct MaintenanceSchedule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The start time of any upcoming scheduled maintenance for this
  /// instance.
  public var startTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The end time of any upcoming scheduled maintenance for this
  /// instance.
  public var endTime: GoogleCloudWKT.Timestamp? = nil

  /// If the scheduled maintenance can be rescheduled, default is true.
  @available(*, deprecated)
  public var canReschedule: Swift.Bool = Swift.Bool()

  /// Output only. The deadline that the maintenance schedule start time can not
  /// go beyond, including reschedule.
  public var scheduleDeadlineTime: GoogleCloudWKT.Timestamp? = nil

  /// Initialize a new instance of `MaintenanceSchedule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MaintenanceSchedule().with { $0.startTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.v1.MaintenanceSchedule"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
