// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// TlsCertificate Resource
public struct TlsCertificate: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Serial number, as extracted from the certificate.
  public var serialNumber: Swift.String = Swift.String()

  /// PEM representation.
  public var cert: Swift.String = Swift.String()

  /// Output only. The time when the certificate was created in [RFC
  /// 3339](https://tools.ietf.org/html/rfc3339) format, for example
  /// `2020-05-18T00:00:00.094Z`.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when the certificate expires in [RFC
  /// 3339](https://tools.ietf.org/html/rfc3339) format, for example
  /// `2020-05-18T00:00:00.094Z`.
  public var expireTime: GoogleWKT.WKTTimestamp? = nil

  /// Sha1 Fingerprint of the certificate.
  public var sha1Fingerprint: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TlsCertificate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TlsCertificate().with { $0.serialNumber = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let serialNumber = CodingKeys(stringValue: "serialNumber")
    static let cert = CodingKeys(stringValue: "cert")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let expireTime = CodingKeys(stringValue: "expireTime")
    static let sha1Fingerprint = CodingKeys(stringValue: "sha1Fingerprint")

    static let _knownKeys: Set<Swift.String> = [
      "serialNumber",
      "cert",
      "createTime",
      "expireTime",
      "sha1Fingerprint",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serialNumber) {
      self.serialNumber = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cert) {
      self.cert = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.expireTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .expireTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sha1Fingerprint) {
      self.sha1Fingerprint = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.serialNumber, forKey: .serialNumber)
    try container.encode(self.cert, forKey: .cert)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.expireTime, forKey: .expireTime)
    try container.encode(self.sha1Fingerprint, forKey: .sha1Fingerprint)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.v1.TlsCertificate"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
