// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for
/// [UpdateInstance][google.cloud.redis.v1.CloudRedis.UpdateInstance].
///
/// [google.cloud.redis.v1.CloudRedis.UpdateInstance]: <doc:CloudRedisClient/updateInstance(request:options:)>
public struct UpdateInstanceRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Mask of fields to update. At least one path must be supplied in
  /// this field. The elements of the repeated paths field may only include these
  /// fields from [Instance][google.cloud.redis.v1.Instance]:
  ///
  ///  *   `displayName`
  ///  *   `labels`
  ///  *   `memorySizeGb`
  ///  *   `redisConfig`
  ///  *   `replica_count`
  ///
  /// [google.cloud.redis.v1.Instance]: <doc:Instance>
  public var updateMask: GoogleWKT.FieldMask? = nil

  /// Required. Update description.
  /// Only fields specified in update_mask are updated.
  public var instance: Instance? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateInstanceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateInstanceRequest().with { $0.updateMask = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let instance = CodingKeys(stringValue: "instance")

    static let _knownKeys: Set<Swift.String> = [
      "updateMask",
      "instance",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.updateMask = try container.decodeIfPresent(GoogleWKT.FieldMask.self, forKey: .updateMask)
    self.instance = try container.decodeIfPresent(Instance.self, forKey: .instance)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encodeIfPresent(self.instance, forKey: .instance)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.v1.UpdateInstanceRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
