// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// Time window in which disruptive maintenance updates occur. Non-disruptive
/// updates can occur inside or outside this window.
public struct WeeklyMaintenanceWindow: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The day of week that maintenance updates occur.
  public var day: GoogleType.DayOfWeek = GoogleType.DayOfWeek()

  /// Required. Start time of the window in UTC time.
  public var startTime: GoogleType.TimeOfDay? = nil

  /// Output only. Duration of the maintenance window. The current window is
  /// fixed at 1 hour.
  public var duration: GoogleCloudWKT.Duration? = nil

  /// Initialize a new instance of `WeeklyMaintenanceWindow`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WeeklyMaintenanceWindow().with { $0.day = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.v1.WeeklyMaintenanceWindow"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
